name: Artofshadia
favicon: null
layout_spectrum: 0.90849
typography_spectrum: 0.6985435660462826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cc0000'
    - '#de5e5e'
    - '#000000'
    - '#484848'
  brandStrength: 0.7172154241707176
  lightness: 0.25
  saturation: 0.45379401789978147
  rhythmicContrast: 0.75
purpose: []
